kill (all);
done;

subst ([], foo (1, 2, 3));
foo (1, 2, 3);

subst (x, y, foo (1, 2, 3));
foo (1, 2, 3);

subst (0, 1, foo (1, 2, 3));
foo (0, 2, 3);

subst (1 = 0, foo (1, 2, 3));
foo (0, 2, 3);

subst ([1 = 0, 2 = 1, 3 = 2], foo (1, 2, 3));
foo (0, 1, 2);

subst ([3 = 2, 2 = 1, 1 = 0], foo (1, 2, 3));
foo (0, 0, 0);

psubst ([], foo (1, 2, 3));
foo (1, 2, 3);

psubst (x, y, foo (1, 2, 3));
foo (1, 2, 3);

psubst (0, 1, foo (1, 2, 3));
foo (0, 2, 3);

psubst (1 = 0, foo (1, 2, 3));
foo (0, 2, 3);

psubst ([1 = 0, 2 = 1, 3 = 2], foo (1, 2, 3));
foo (0, 1, 2);

psubst ([3 = 2, 2 = 1, 1 = 0], foo (1, 2, 3));
foo (0, 1, 2);

block ([substitution_applies_lambda : true],
  subst (f = lambda ([x], 2*x), f (u)));
2 * u;

block ([substitution_applies_lambda : false],
  subst (f = lambda ([x], 2*x), f (u)));
lambda ([x], 2*x) (u);


