files='Affine.texi
alt-display.texi
Arrays.texi
asympa.texi
Atensor.texi
augmented_lagrangian.texi
bernstein.texi
bitwise.texi
bode.texi
Bugs.texi
celine.texi
clebsch_gordan.texi
cobyla.texi
combinatorics.texi
commandline-options.texi
Command.texi
contrib_ode.texi
Ctensor.texi
Database.texi
DataTypes.texi
Debugging.texi
defstruct.texi
Deleted.texi
descriptive.texi
Differential.texi
Differentiation.texi
drawdf.texi
draw.texi
dynamics.texi
engineering-format.texi
Equations.texi
errormessages.texi
Evaluation.texi
Expressions.texi
ezunits.texi
f90.texi
finance.texi
fractals.texi
Function.texi
gentran.texi
ggf.texi
graphs.texi
grobner.texi
Groups.texi
Help.texi
hompack.texi
impdiff.texi
include-maxima.texi
Input.texi
Integration.texi
interpol.texi
Introduction.texi
Itensor.texi
lapack.texi
lbfgs.texi
Limits.texi
lindstedt.texi
linearalgebra.texi
Lists.texi
lsquares.texi
makeOrders.texi
MathFunctions.texi
Matrices.texi.m4
maxima.texi
minpack.texi
Miscellaneous.texi
mnewton.texi
nset.texi
Number.texi
numericalio.texi
Numerical.texi
odepack.texi
operatingsystem.texi
Operators.texi
opsubst.texi
Plotting.texi
Polynomials.texi
Program.texi
pslq.texi
pytranslate.texi
quantum_computing.texi
ratpow.texi
romberg.texi
Rules.texi
Runtime.texi
Series.texi
simplex.texi
simplifications.texi
Simplification.texi
solve_rec.texi
stats.texi
stirling.texi
stringproc.texi
Symmetries.texi
to_poly_solve.texi
unit.texi
wrstcse.texi
zeilberger.texi
Constants.texi.m4
distrib.texi.m4
Elliptic.texi.m4
orthopoly.texi.m4
Special.texi.m4'

for f in $files;
do
    echo $f
    awk -f cvt-cat.awk $f > foo
    mv foo $f
done

