#!/usr/bin/perl

# Skip everything until the first blank line
while (my $line = <>) {
    last if $line =~ /^$/;
}

print "\@c This file has been autogenerated from a .po file containing translations.\n";

$snippetline = "";
$snippet = "";
$msgid = "";
$msgstr = "";
    
# Now work through the whole file
while (my $line = <>) {

    # Handle lines containing text
    if ($line =~ /^".*"$/)
    {
	$snippetline = $line;
	$snippetline =~ s/^"(.*)"$/\1/g;
	$snippetline =~ s/\\n$//g;
	$snippet.= $snippetline;
    }
    
    if ($line =~ /^msgstr +""$/)
    {
	$msgid = $snippet;
	$snippet = "";
    }

    if (($line =~ /^msgid +""$/) || ($line =~ /^$/))
    {
	$msgstr = $snippet;
	if ($msgstr eq "")
	{
	    $msgstr = $msgid;
	}
	if ($msgstr ne "")
	{
	    print $msgstr;
	}

	$msgid = "";
	$msgstr = "";
	$snippet = "";
    }
}

# Print the last translation if the file didn't end in a newline.
if ($msgstr eq "")
{
    $msgstr = $msgid;
}
if ($msgstr ne "")
{
    print $msgstr;
}

